

services:
  dev-db:
    image: mongo:latest
    container_name: ecommerce-mongo-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce-dev
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: